FROM ubuntu:bionic as gpuDeps

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb && \
  dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb && \
  apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \
  apt-get update && \
  wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
  apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
  apt-get update && \
  apt-get install --no-install-recommends nvidia-driver-410 && \
  apt-mark hold nvidia-driver-410

