balena:
  image: alpine:latest
  only:
    - master
  stage: deploy
  script:
    - apk add git openssh
    - mkdir -p ~/.ssh
    - echo "$RADIO_RSA" > ~/.ssh/id_rsa
    - echo "$RADIO_RSA_PUB" > ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa && eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan git.balena-cloud.com >> ~/.ssh/known_hosts
    - git remote add balena gh_kazazes@git.balena-cloud.com:gh_kazazes/skyscraper.git
    - git push balena master

google_source:
  image: google/cloud-sdk
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - git config --global credential.'https://source.developers.google.com'.helper gcloud.sh
  - git remote add google https://source.developers.google.com/p/skyscraper-sdr/r/skyscraper-edge-mirror
  - git push -f google master
