steps:
- name: 'gcr.io/$PROJECT_ID/slackbot'
  args: [ '--build', '$BUILD_ID',
  '--webhook', 'https://hooks.slack.com/services/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' ]
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/config:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/config:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/config:latest', '-f', './edge-images/config/amd64.dockerfile', './edge-images/config']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/config:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/datadog:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/datadog:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/datadog:latest', '-f', './edge-images/datadog/amd64.dockerfile', './edge-images/datadog']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/datadog:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest', '-f', './edge-images/dump1090/amd64.dockerfile', './edge-images/dump1090']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/electron:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/electron:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/electron:latest', '-f', './edge-images/electron/amd64.dockerfile', './edge-images/electron']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/electron:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest', '-f', './edge-images/mqtt/amd64.dockerfile', './edge-images/mqtt']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/nginx:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/nginx:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/nginx:latest', '-f', './edge-images/nginx/amd64.dockerfile', './edge-images/nginx']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/nginx:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest', '-f', './edge-images/ngrok/amd64.dockerfile', './edge-images/ngrok']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/node-red:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/node-red:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/node-red:latest', '-f', './edge-images/node-red/amd64.dockerfile', './edge-images/node-red']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/node-red:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/redis:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/redis:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/redis:latest', '-f', './edge-images/redis/amd64.dockerfile', './edge-images/redis']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/redis:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/samba:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/samba:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/samba:latest', '-f', './edge-images/samba/amd64.dockerfile', './edge-images/samba']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/samba:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest', '-f', './edge-images/trunk-recorder/amd64.dockerfile', './edge-images/trunk-recorder']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest']
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['-']
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/methodical-tea-237508/skyscraperai/window-manager:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/window-manager:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/window-manager:latest', '-f', './edge-images/window-manager/amd64.dockerfile', './edge-images/window-manager']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/window-manager:latest']
timeout: 3600s
images: ['gcr.io/methodical-tea-237508/skyscraperai/window-manager:latest', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest', 'gcr.io/methodical-tea-237508/skyscraperai/samba:latest', 'gcr.io/methodical-tea-237508/skyscraperai/redis:latest', 'gcr.io/methodical-tea-237508/skyscraperai/node-red:latest', 'gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest', 'gcr.io/methodical-tea-237508/skyscraperai/nginx:latest', 'gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest', 'gcr.io/methodical-tea-237508/skyscraperai/electron:latest', 'gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest', 'gcr.io/methodical-tea-237508/skyscraperai/datadog:latest', 'gcr.io/methodical-tea-237508/skyscraperai/config:latest', ]
