steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/skyscraper-sdr/github.com/kazazes/skyscraper",
        "-f",
        "./base-images/pybombs-minimal/armhf.dockerfile",
        "./base-images/pybombs-minimal/",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/skyscraper-sdr/github.com/kazazes/skyscraper"]
options:
  machineType: "N1_HIGHCPU_32"
images: ["gcr.io/skyscraper-sdr/github.com/kazazes/skyscraper"]
