steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/adsb-mqtt:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/adsb-mqtt:latest', '-f', './host-images/adsb-mqtt/amd64.dockerfile', './host-images/adsb-mqtt']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/adsb-mqtt:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/certbot:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/certbot:latest', '-f', './host-images/certbot/amd64.dockerfile', './host-images/certbot']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/certbot:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/config:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/config:latest', '-f', './host-images/config/amd64.dockerfile', './host-images/config']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/config:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/data-router:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/data-router:latest', '-f', './host-images/data-router/amd64.dockerfile', './host-images/data-router']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/data-router:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/datadog:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/datadog:latest', '-f', './host-images/datadog/amd64.dockerfile', './host-images/datadog']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/datadog:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/debugger:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/debugger:latest', '-f', './host-images/debugger/amd64.dockerfile', './host-images/debugger']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/debugger:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest', '-f', './host-images/dump1090/amd64.dockerfile', './host-images/dump1090']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/manager:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/manager:latest', '-f', './host-images/manager/amd64.dockerfile', './host-images/manager']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/manager:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest', '-f', './host-images/mqtt/amd64.dockerfile', './host-images/mqtt']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/nginx:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/nginx:latest', '-f', './host-images/nginx/amd64.dockerfile', './host-images/nginx']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/nginx:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest', '-f', './host-images/ngrok/amd64.dockerfile', './host-images/ngrok']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/node-red:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/node-red:latest', '-f', './host-images/node-red/amd64.dockerfile', './host-images/node-red']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/node-red:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/openvpn:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/openvpn:latest', '-f', './host-images/openvpn/amd64.dockerfile', './host-images/openvpn']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/openvpn:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/postgres:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/postgres:latest', '-f', './host-images/postgres/amd64.dockerfile', './host-images/postgres']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/postgres:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/prometheus:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/prometheus:latest', '-f', './host-images/prometheus/amd64.dockerfile', './host-images/prometheus']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/prometheus:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/rabbitmq:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/rabbitmq:latest', '-f', './host-images/rabbitmq/amd64.dockerfile', './host-images/rabbitmq']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/rabbitmq:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/redis:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/redis:latest', '-f', './host-images/redis/amd64.dockerfile', './host-images/redis']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/redis:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/samba:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/samba:latest', '-f', './host-images/samba/amd64.dockerfile', './host-images/samba']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/samba:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/sdrangel:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/sdrangel:latest', '-f', './host-images/sdrangel/amd64.dockerfile', './host-images/sdrangel']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/sdrangel:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/sdrangelcli:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/sdrangelcli:latest', '-f', './host-images/sdrangelcli/amd64.dockerfile', './host-images/sdrangelcli']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/sdrangelcli:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/srslte:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/srslte:latest', '-f', './host-images/srsLTE/amd64.dockerfile', './host-images/srsLTE']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/srslte:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-player:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-player:latest', '-f', './host-images/trunk-player/amd64.dockerfile', './host-images/trunk-player']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-player:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest', '-f', './host-images/trunk-recorder/amd64.dockerfile', './host-images/trunk-recorder']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/watchdog:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/watchdog:latest', '-f', './host-images/watchdog/amd64.dockerfile', './host-images/watchdog']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/watchdog:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/webrx:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/webrx:latest', '-f', './host-images/webrx/amd64.dockerfile', './host-images/webrx']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/webrx:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/methodical-tea-237508/skyscraperai/wifi-connect:latest', '-t', 'gcr.io/methodical-tea-237508/skyscraperai/wifi-connect:latest', '-f', './host-images/wifi-connect/amd64.dockerfile', './host-images/wifi-connect']
  timeout: 600s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/methodical-tea-237508/skyscraperai/wifi-connect:latest']
