steps:
- name: 'gcr.io/$PROJECT_ID/slackbot'
  args: [ '--build', '$BUILD_ID',
  '--webhook', 'https://hooks.slack.com/services/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' ]
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/config:latest', '--context=dir://workspace/./edge-images/config', '--dockerfile=/workspace/./edge-images/config/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest', '--context=dir://workspace/./edge-images/dump1090', '--dockerfile=/workspace/./edge-images/dump1090/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/dump1090-mqtt:latest', '--context=dir://workspace/./edge-images/dump1090-mqtt', '--dockerfile=/workspace/./edge-images/dump1090-mqtt/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest', '--context=dir://workspace/./edge-images/mqtt', '--dockerfile=/workspace/./edge-images/mqtt/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/nginx:latest', '--context=dir://workspace/./edge-images/nginx', '--dockerfile=/workspace/./edge-images/nginx/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest', '--context=dir://workspace/./edge-images/ngrok', '--dockerfile=/workspace/./edge-images/ngrok/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/node-red:latest', '--context=dir://workspace/./edge-images/node-red', '--dockerfile=/workspace/./edge-images/node-red/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/redis:latest', '--context=dir://workspace/./edge-images/redis', '--dockerfile=/workspace/./edge-images/redis/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/samba:latest', '--context=dir://workspace/./edge-images/samba', '--dockerfile=/workspace/./edge-images/samba/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest', '--context=dir://workspace/./edge-images/trunk-recorder', '--dockerfile=/workspace/./edge-images/trunk-recorder/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/wifi-connect:latest', '--context=dir://workspace/./edge-images/wifi-connect', '--dockerfile=/workspace/./edge-images/wifi-connect/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=12h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/window-manager:latest', '--context=dir://workspace/./edge-images/window-manager', '--dockerfile=/workspace/./edge-images/window-manager/amd64.dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=72h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/gc-to-balena:latest', '--context=dir://workspace/./host-images/gc-to-balena', '--dockerfile=/workspace/./host-images/gc-to-balena/Dockerfile']
  timeout: 1200s
  waitFor: ['-']
- name: 'gcr.io/methodical-tea-237508/skyscraperai/gc-to-balena:latest'
timeout: 3600s
