steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/skyscraper-sdr/github.com/kazazes/skyscraper",
        "-f",
        "./base-images/pybombs-minimal/armhf.dockerfile",
        "./base-images/pybombs-minimal/",
      ]
    timeout: 8h
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/skyscraper-sdr/github.com/kazazes/skyscraper"]
images: ["gcr.io/skyscraper-sdr/github.com/kazazes/skyscraper"]
timeout: 8h30m
