steps:
- name: 'gcr.io/$PROJECT_ID/slackbot'
  args: [ '--build', '$BUILD_ID',
  '--webhook', 'https://hooks.slack.com/services/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' ]
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/backend:latest', '--context=dir://workspace/./edge-images/backend', '--dockerfile=/workspace/./edge-images/backend/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/config:latest', '--context=dir://workspace/./edge-images/config', '--dockerfile=/workspace/./edge-images/config/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/frontend:latest', '--context=dir://workspace/./edge-images/frontend', '--dockerfile=/workspace/./edge-images/frontend/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest', '--context=dir://workspace/./edge-images/mqtt', '--dockerfile=/workspace/./edge-images/mqtt/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/nginx:latest', '--context=dir://workspace/./edge-images/nginx', '--dockerfile=/workspace/./edge-images/nginx/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest', '--context=dir://workspace/./edge-images/ngrok', '--dockerfile=/workspace/./edge-images/ngrok/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/node-red:latest', '--context=dir://workspace/./edge-images/node-red', '--dockerfile=/workspace/./edge-images/node-red/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/redis:latest', '--context=dir://workspace/./edge-images/redis', '--dockerfile=/workspace/./edge-images/redis/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--cache=true', '--cache-ttl=48h', '--destination=gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest', '--context=dir://workspace/./edge-images/trunk-recorder', '--dockerfile=/workspace/./edge-images/trunk-recorder/Dockerfile']
  timeout: 3400s
  waitFor: ['-']
timeout: 4200s
