version: "2.1"
volumes:
  resin-data: {}
  portainer_data: {}
services:
  # prometheus:
  #   cpu_shares: 40
  #   build:
  #     context: ./host-images/prometheus
  #   privileged: true
  #   pid: host
  #   restart: always
  #   ports:
  #     - 8080:8080
  manager:
    container_name: manager
    cpuset: "0-3"
    build:
      context: ./host-images/manager
    privileged: true
    pid: host
    restart: always
    environment:
      - "NODE_ENV=production"
    volumes:
      - "resin-data:/data"
    ports:
      - 3000:3000
  trunk-recorder:
    container_name: trunk-recorder
    cpuset: "0-7"
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: unless-stopped
    depends_on:
      - "config"
    network_mode: host
    mem_swappiness: 10
    cap_add:
      - SYS_RAWIO
    volumes:
      - "resin-data:/data"
    environment:
      - RECORDER_CONF
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
  # mqtt:
  #   image: panuwitp/mosquitto-arm
  #   ports:
  #     - "1883:1883"
  node-red:
    container_name: node-red
    cpuset: "0-3"
    build:
      context: ./host-images/node-red
    volumes:
      - "resin-data:/data"
    ports:
      - "1880:1880"
    depends_on:
      - mqtt
    restart: always
  nginx:
    cpuset: "0-3"
    build:
      context: ./host-images/nginx
    privileged: true
    depends_on:
      - manager
      - prometheus
    ports:
      - "80:80"
      - "443:443"
    restart: always
  debugger:
    cpu_shares: 40
    cpuset: "0"
    build:
      context: ./host-images/debugger
    command: "exit 0"
    restart: "no"
    privileged: true
    volumes:
      - "resin-data:/data"
  portainer:
    image: portainer/portainer
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:9000"
  # wifi-connect:
  #   build:
  #     context: ./host-images/wifi-connect
  #   restart: no
  #   privileged: true
  #   network_mode: "host"
  #   labels:
  #     io.resin.features.dbus: "1"
