version: "2"
volumes:
  resin-data: {}
services:
  sysdig:
    name: sysdig-agent
    restart: always
    privileged: true
    network_mode: host
    pid: host
    environment:
      - ACCESS_KEY=9b98a2e6-f13c-4b72-9fc9-997fb4cd02b3
      - SECURE=true
      - TAGS=ss1:node
    volumes:
      - /lib/modules:/host/lib/modules:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
      # /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro  /usr:/host/usr:ro --
    shm_size: 512m
    image: sysdig/agent
    labels:
      io.balena.features.balena-socket: "1"
      io.balena.features.kernel-modules: "1"
  mqtt:
    image: gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest
    container_name: mqtt
    user: root
    ports:
      - "1883:1883"
    volumes:
      - "resin-data:/data"
  config:
    image: gcr.io/methodical-tea-237508/skyscraperai/config:latest
    container_name: config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
  datarouter:
    image: gcr.io/methodical-tea-237508/skyscraperai/backend:latest
    container_name: datarouter
    volumes:
      - "resin-data:/data"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - ENABLE_UPLOAD=true
      - GCP_PROJECT_ID=methodical-tea-237508
      - GCP_REGION=us-central1
      - ENGINE_API_KEY=service:skyscraper:vzyaqidtNPEdZasGdbPdaA
      - GOOGLE_APPLICATION_CREDENTIALS=/data/certs/gcp.json
      - GRAPHQL_PORT=4000
      - MQTT_HOST=mqtt.skyscraper.ai
      - MQTT_PASSWORD=Ur6yANnx@ZD
      - MQTT_PORT=1883
      - MQTT_USERNAME=edge
      - MQTT_UPSTREAM_HOST=mqtt://skyscraper.ai
      - PRISMA_ENDPOINT=https://us1.prisma.sh/peter-k/skyscraper/dev
      - PRISMA_SECRET=scrapingskies
      - SENTRY_URI=https://4ac277bd085b4acbbaa74de8c33202b2@sentry.io/1441821
      - REDIS_HOST=redis
    depends_on:
      - redis
  dump1090:
    image: gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest
    container_name: dump1090
    privileged: true
    volumes:
      - "resin-data:/data"
    ports:
      - "30003:30003"
    restart: always
  dump1090-mqtt:
    image: gcr.io/methodical-tea-237508/skyscraperai/dump1090-mqtt:latest
    container_name: dump1090-mqtt
    volumes:
      - "resin-data:/data"
    depends_on:
      - mqtt
      - dump1090
    restart: always
  netdata:
    image: skyscraperai/netdata
    container_name: netdata
    hostname: edge.sibyl.vision
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
  nginx:
    image: gcr.io/methodical-tea-237508/skyscraperai/nginx:latest
    container_name: nginx
    depends_on:
      - manager
      - nodered
      - netdata
      - datarouter
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "resin-data:/data"
  nodered:
    image: gcr.io/methodical-tea-237508/skyscraperai/node-red:latest
    container_name: nodered
    volumes:
      - "resin-data:/data"
    ports:
      - "1880:1880"
    environment:
      - NODE_ENV=production
    restart: always
  ngrok:
    image: gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest
    links:
      - nginx:https
    container_name: ngrok
    privileged: false
    depends_on:
      - nginx
    command: ngrok tls -region=us -authtoken=iiX4RYrrdFWgU9pdDEnR_4qRcocGF5v9E3SjGmys7L -hostname=edge.sibyl.vision nginx:443
  manager:
    image: gcr.io/methodical-tea-237508/skyscraperai/frontend:latest
    container_name: manager
    volumes:
      - "resin-data:/data"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - NETDATA_HTTP=https://edge.sibyl.vision/netdata/
      - GRAPHQL_HTTP=https://edge.sibyl.vision/graphql/
      - GRAPHQL_WS=wss://edge.sibyl.vision/graphql/
      - GOOGLE_APPLICATION_CREDENTIALS=/data/config/certs/gcp.json
    restart: always
  redis:
    image: gcr.io/methodical-tea-237508/skyscraperai/redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    restart: always
  trunk-recorder:
    image: gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest
    privileged: true
    depends_on:
      - "config"
    volumes:
      - "resin-data:/data"
    environment:
      - RECORDER_CONF=sites/SF-PK/config.json
      - SHORTNAME=SFPD
      - MQTT_PASSWORD=Ur6yANnx@ZD
      - MQTT_PORT=1883
      - MQTT_USERNAME=edge
      - MQTT_HOST=127.0.0.1
    restart: on-failure



