version: "2.1"
networks:
  frontend:
    driver: bridge
volumes:
  resin-data: {}
services:
  manager:
    build:
      context: ./host-images/manager
    privileged: true
    pid: host
    restart: always
    volumes:
      - "resin-data:/data"
    ports:
      - 3000:3000
    networks:
      - frontend
  trunk-recorder:
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: unless-stopped
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  node-red:
    build:
      context: ./host-images/node-red
    volumes:
      - "resin-data:/data"
    ports:
      - "1880:1880"
    depends_on:
      - mqtt
    restart: always
    networks:
      - frontend
  nginx:
    build:
      context: ./host-images/nginx
    privileged: true
    depends_on:
      - node-red
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    restart: always
  debug:
    image: pckzs/pybombs
    command: "sleep infinity"
    privileged: true
    volumes:
      - "resin-data:/data"
