version: "2.1"
volumes:
  resin-data: {}
services:
  prometheus:
    cpu_shares: 40
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/prometheus
    privileged: true
    pid: host
    restart: always
    ports:
      - 8080:8080
  manager:
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/manager
    privileged: true
    pid: host
    restart: always
    environment:
      - "NODE_ENV=production"
    volumes:
      - "./data:/data"
    ports:
      - 3000:3000
  trunk-recorder:
    cpu_shares: 1000
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/trunk-recorder
    privileged: true
    restart: unless-stopped
    depends_on:
      - "config"
    network_mode: host
    mem_swappiness: 10
    cap_add:
      - SYS_RAWIO
    volumes:
      - "./data:/data"
    environment:
      - RECORDER_CONF
  config:
    cpu_shares: 40
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "./data:/data"
  nginx:
    cpu_shares: 40
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/nginx
    privileged: true
    depends_on:
      - manager
      - prometheus
    ports:
      - "80:80"
      - "443:443"
    restart: always
  debugger:
    cpu_shares: 40
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/debugger
    command: "exit 0"
    restart: "no"
    privileged: true
    volumes:
      - "./data:/data"
