version: "2.1"
volumes:
  resin-data: {}
services:
  trunk-recorder:
    container_name: trunk-recorder
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/trunk-recorder
    privileged: true
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "./data:/data"
    environment:
      - RECORDER_CONF
  config:
    container_name: config
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "./data:/data"
  manager:
    container_name: manager
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/manager
    volumes:
      - "./data:/data"
    ports:
      - 3000
    environment:
      - APP_ID=backend
      - PORT=3000
      - LOG_LEVEL=debug
      - REQUEST_LIMIT=100kb
      - SESSION_SECRET=mySecret
      - SWAGGER_API_SPEC=/spec
      - NODE_ENV=production
  nginx:
    container_name: nginx
    depends_on:
      - manager
    build:
      dockerfile: amd64.dockerfile
      context: host-images/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
  openvpn:
    container_name: openvpn
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/openvpn
    privileged: true
    volumes:
      - "./data:/data"
    restart: always
  watchdog:
    container_name: watchdog
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/watchdog
    privileged: true
    volumes:
      - "./data:/data"
    restart: always
