version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    build:
      context: ./trunk-recorder
    privileged: true
    restart: "no"
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
  config:
    build:
      context: ./config
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
