version: "2.1"
volumes:
  resin-data: {}
services:
  postgres:
    build:
      context: ./host-images/postgres
    volumes:
      - "resin-data:/data"
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: skyscraper
      POSTGRES_PASSWORD: sdr
      PGDATA: /data/postgres
      POSTGRES_DB: radio
  # prisma:
  #   image: prismagraphql/prisma
  #   restart: always
  #   ports:
  #     - "4466:4466"
  #   environment:
  #     PRISMA_CONFIG: |
  #       managementApiSecret: scrapingskies
  #       port: 4466
  #       databases:
  #         default:
  #           connector: postgres
  #           migrations: true
  #           host: postgres
  #           port: 5432
  #           user: skyscraper
  #           password: sdr
  manager:
    build:
      context: ./host-images/manager
    privileged: true
    pid: host
    restart: always
    environment:
      - "NODE_ENV=production"
    volumes:
      - "resin-data:/data"
    ports:
      - 3000:3000
  trunk-recorder:
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: unless-stopped
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  node-red:
    build:
      context: ./host-images/node-red
    volumes:
      - "resin-data:/data"
    ports:
      - "1880:1880"
    depends_on:
      - mqtt
    restart: always
  nginx:
    build:
      context: ./host-images/nginx
    privileged: true
    depends_on:
      - node-red
    ports:
      - "80:80"
      - "443:443"
    restart: always
    links:
      - manager
  debug:
    image: pckzs/pybombs
    command: "sleep infinity"
    privileged: true
    volumes:
      - "resin-data:/data"
