version: "2.1"
volumes:
  resin-data: {}
services:
  trunk-recorder:
    container_name: trunk-recorder
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
    environment:
      - RECORDER_CONF
  config:
    container_name: config
    build:
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
  manager:
    container_name: manager
    build:
      context: ./host-images/manager
    volumes:
      - "resin-data:/data"
    ports:
      - 3000
    environment:
      - APP_ID=backend
      - PORT=3000
      - LOG_LEVEL=debug
      - REQUEST_LIMIT=100kb
      - SESSION_SECRET=mySecret
      - SWAGGER_API_SPEC=/spec
  proxy:
    container_name: proxy
    depends_on:
      - manager
    build:
      context: host-images/proxy
    ports:
      - "80:80"
    restart: always
  openvpn:
    container_name: openvpn
    build:
      context: ./host-images/openvpn
    privileged: true
    volumes:
      - "resin-data:/data"
    restart: always
  watchdog:
    container_name: watchdog
    build:
      context: ./host-images/watchdog
    privileged: true
    volumes:
      - "resin-data:/data"
    restart: always
