version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: "no"
    depends_on:
      - "config"
    network_mode: host
    cpuset: 0-3
    volumes:
      - "resin-data:/data"
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
  influxdb:
    build: influxdb
    container_name: influxdb
    # privileged added so usb drive can be mounted.
    privileged: true
    volumes:
      - "resin-data:/data"
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089"
    restart: always
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    build: telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: "1"
    depends_on:
      - influxdb
    restart: always
  grafana:
    build: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: always
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  mqtt-test:
    image: panuwitp/mosquitto-arm
    ports:
      - "1884:1883"
  node-red:
    build: node-red
    volumes:
      - "resin-data:/data"
    ports:
      - "1880:1880"
    depends_on:
      - mqtt
    restart: always
  nginx:
    build: nginx
    depends_on:
      - grafana
      - node-red
    ports:
      - "80:80"
      - "443:443"
    restart: always
