version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/trunk-recorder
    privileged: true
    restart: unless-stopped
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "./data:/data"
  config:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "./data:/data"
  influxdb:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/influxdb
    container_name: influxdb
    privileged: true
    volumes:
      - "./data:/data"
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089"
    restart: always
  telegraf:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: "1"
    depends_on:
      - influxdb
    restart: always
  grafana:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: always
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  node-red:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/node-red
    volumes:
      - "./data:/data"
    ports:
      - "1880:1880"
    depends_on:
      - mqtt
    restart: always
  nginx:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/nginx
    depends_on:
      - grafana
      - node-red
    ports:
      - "80:80"
      - "443:443"
    restart: always
  debug:
    image: pckzs/pybombs
    command: "sleep infinity"
    volumes:
      - "./data:/data"
