version: "2"
volumes:
  resin-data: {}
services:
  mqtt:
    container_name: mqtt
    build:
      context: ./host-images/mqtt
    volumes:
      - "resin-data:/data"
    restart: always
    ports:
      - "1883"
  netdata:
    image: sibylvision/netdata
    container_name: netdata
    hostname: edge.sibyl.vision
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
  trunk-recorder:
    image: skyscraperai/trunk-recorder
    privileged: true
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
    environment:
      - RECORDER_CONF=sites/SF-PK/config.json
      - SHORTNAME=SFPD
      - MQTT_HOST=mqtt
    restart: on-failure
  ngrok:
    links:
      - nginx:https
    container_name: ngrok
    build:
      context: ./host-images/ngrok
    privileged: false
    depends_on:
      - nginx
    command: ngrok tls -region=us -authtoken=iiX4RYrrdFWgU9pdDEnR_4qRcocGF5v9E3SjGmys7L -hostname=edge.sibyl.vision nginx:443
  config:
    container_name: config
    build:
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
  manager:
    container_name: manager
    build:
      context: ./host-images/manager
    volumes:
      - "resin-data:/data"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - NETDATA_HTTP=https://edge.sibyl.vision/netdata/
      - GRAPHQL_HTTP=https://edge.sibyl.vision/graphql/
      - GRAPHQL_WS=wss://edge.sibyl.vision/graphql/
    restart: always
  datarouter:
    container_name: datarouter
    build:
      context: ./host-images/data-router
    volumes:
      - "resin-data:/data"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - GRAPHQL_PORT=4000
      - MQTT_PORT=1883
    depends_on:
      - redis
  nginx:
    container_name: nginx
    depends_on:
      - manager
      - nodered
      - netdata
    build:
      context: host-images/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "resin-data:/data"
  nodered:
    container_name: nodered
    build:
      context: ./host-images/node-red
    volumes:
      - "resin-data:/data"
    ports:
      - "1880:1880"
    environment:
      - NODE_ENV=production
    restart: always
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    container_name: redis
    volumes:
      - "resin-data:/data"
    ports:
      - "6379"
    restart: always
  prometheus:
    build:
      context: ./host-images/prometheus
    container_name: prometheus
    privileged: true
    ports:
      - "8888:80"
    volumes:
      - "resin-data:/data"
#  dump1090:
#    build:
#      context: ./host-images/dump1090
#    container_name: dump1090
#    volumes:
#      - "resin-data:/data"
#    ports:
#      - "30002:30002"
#    restart: always
#  sdrangel:
#    build:
#      context: "./host-images/sdrangel"
#    container_name: sdrangel
#    ports:
#      - "8091:8091"
#      - "10011:10011/udp"
#    environment:
#      - PULSE_SERVER=unix:/run/user/1000/pulse/native
#      - UDP_PORT=10011
#      - API_PORT=1880
#      - RX_BITS=24
#  sdrangelcli:
#    build:
#      context: "./host-images/sdrangelcli"
#    container_name: "sdrangelcli"
#    ports:
#      - "8888:8080"
#    environment:
#      - UDP_PORT=10011
#      - API_PORT=1880
#      - RX_BITS=24
