version: "2.1"
networks: {}
volumes:
  resin-data:
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
services:
  trunk-recorder:
    build:
      dockerfile: amd64.dockerfile
      context: ./host-images/trunk-recorder
    privileged: true
    restart: "no"
    network_mode: host
    volumes:
      - "resin-data:/data"
