version: "2"
volumes:
  balena-data: {}
services:
  config:
    image: gcr.io/methodical-tea-237508/skyscraperai/config:latest
    network_mode: host
    restart: "on-failure"
    volumes:
      - "balena-data:/data"
  redis:
    image: gcr.io/methodical-tea-237508/skyscraperai/redis:latest
    privileged: true
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "balena-data:/data"
    restart: "on-failure"
    command: /data/conf/redis.conf
  netdata:
    image: skyscraperai/netdata
    container_name: netdata
    hostname: edge.sibyl.vision
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
  x11:
    image: gcr.io/methodical-tea-237508/skyscraperai/window-manager:latest
    restart: always
    privileged: true
    labels:
      io.balena.features.dbus: '1'


