version: "2"
volumes:
  resin-data: {}
services:
  mqtt:
    image: gcr.io/methodical-tea-237508/skyscraperai/mqtt:latest
    container_name: mqtt
    volumes:
      - "resin-data:/data"
    restart: always
    ports:
      - "1883"
  samba:
    image: gcr.io/methodical-tea-237508/skyscraperai/samba:latest
    container_name: samba
    volumes:
      - "resin-data:/data"
    network_mode: host
  netdata:
    image: skyscraperai/netdata
    container_name: netdata
    hostname: edge.sibyl.vision
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
  trunk-recorder:
    image: gcr.io/methodical-tea-237508/skyscraperai/trunk-recorder:latest
    privileged: true
    depends_on:
      - "config"
    volumes:
      - "resin-data:/data"
    environment:
      - RECORDER_CONF=sites/SF-PK/config.json
      - SHORTNAME=SFPD
      - MQTT_HOST=mqtt
    restart: on-failure
  # lte-site:
  #   build:
  #     context: ./host-images/srsLTE
  #   privileged: true
  #   depends_on:
  #     - "config"
  #   volumes:
  #     - "resin-data:/data"
  #   restart: on-failure
  #   pid: host
  #   network_mode: host
  ngrok:
    image: gcr.io/methodical-tea-237508/skyscraperai/ngrok:latest
    links:
      - nginx:https
    container_name: ngrok
    privileged: false
    depends_on:
      - nginx
    command: ngrok tls -region=us -authtoken=iiX4RYrrdFWgU9pdDEnR_4qRcocGF5v9E3SjGmys7L -hostname=edge.sibyl.vision nginx:443
  config:
    image: gcr.io/methodical-tea-237508/skyscraperai/config:latest
    container_name: config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
  manager:
    image: gcr.io/methodical-tea-237508/skyscraperai/manager:latest
    container_name: manager
    volumes:
      - "resin-data:/data"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - NETDATA_HTTP=https://edge.sibyl.vision/netdata/
      - GRAPHQL_HTTP=https://edge.sibyl.vision/graphql/
      - GRAPHQL_WS=wss://edge.sibyl.vision/graphql/
      - GOOGLE_APPLICATION_CREDENTIALS=/data/config/certs/gcp.json
    restart: always
  datarouter:
    image: gcr.io/methodical-tea-237508/skyscraperai/data-router:latest
    container_name: datarouter
    volumes:
      - "resin-data:/data"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - GRAPHQL_PORT=4000
      - MQTT_PORT=1883
    depends_on:
      - redis
  nginx:
    image: gcr.io/methodical-tea-237508/skyscraperai/nginx:latest
    container_name: nginx
    depends_on:
      - manager
      - nodered
      - netdata
      - datarouter
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "resin-data:/data"
  nodered:
    image: gcr.io/methodical-tea-237508/skyscraperai/node-red:latest
    container_name: nodered
    build:
      context: ./host-images/node-red
    volumes:
      - "resin-data:/data"
    ports:
      - "1880:1880"
    environment:
      - NODE_ENV=production
    restart: always
  redis:
    image: redis
    command: redis-server --appendonly yes
    container_name: redis
    volumes:
      - "resin-data:/data"
    ports:
      - "6379"
    restart: always
  # prometheus:
  #   build:
  #     context: ./host-images/prometheus
  #   container_name: prometheus
  #   privileged: true
  #   ports:
  #     - "8888:80"
  #   volumes:
  #     - "resin-data:/data"
  dump1090:
    image: gcr.io/methodical-tea-237508/skyscraperai/dump1090:latest
    container_name: dump1090
    privileged: true
    volumes:
      - "resin-data:/data"
    ports:
      - "30002:30002"
    restart: always
#  sdrangel:
#    build:
#      context: "./host-images/sdrangel"
#    container_name: sdrangel
#    ports:
#      - "8091:8091"
#      - "10011:10011/udp"
#    environment:
#      - PULSE_SERVER=unix:/run/user/1000/pulse/native
#      - UDP_PORT=10011
#      - API_PORT=1880
#      - RX_BITS=24
#  sdrangelcli:
#    build:
#      context: "./host-images/sdrangelcli"
#    container_name: "sdrangelcli"
#    ports:
#      - "8888:8080"
#    environment:
#      - UDP_PORT=10011
#      - API_PORT=1880
#      - RX_BITS=24
