version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    cpu_shares: 10
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: "no"
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
  config:
    cpu_shares: 1
    build:
      context: ./host-images/config
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
  data-browser:
    cpu_shares: 1
    build:
      context: ./host-images/data-browser
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
