version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/trunk-recorder
    privileged: true
    restart: "no"
    depends_on:
      - "config"
    network_mode: host
    cpuset: 0-3
    volumes:
      - "./data:/data"
  config:
    build:
      dockerfile:  amd64.dockerfile
      context: ./host-images/config
    network_mode: host
    restart: "no"
    volumes:
      - "./data:/data"
