version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: "no"
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
  trunk-player:
    build:
      context: ./host-images/trunk-player
    network_mode: host
    restart: "no"
    depends_on:
      - "redis"
      - "postgres"
      - "nginx"
    volumes:
      - "resin-data:/data"
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
  data-browser:
    build:
      context: ./host-images/data-browser
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
  postgres:
    build:
      context: ./host-images/postgres
    volumes:
      - "resin-data:/data"
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: skyscraper
      POSTGRES_PASSWORD: sdr
      PGDATA: /data/postgres
      POSTGRES_DB: radio
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
  redis:
    build:
      context: ./host-images/redis
    volumes:
      - "resin-data:/data"
    restart: "no"
    network_mode: host
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
  nginx:
    build:
      context: ./host-images/nginx
    privileged: true
    volumes:
      - "resin-data:/data"
    restart: "no"
    network_mode: host
    ports:
      - 80:80
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
  filebrowser:
    image: filebrowser/filebrowser
    privileged: true
    volumes:
      - "resin-data:/data"
    restart: "no"
    network_mode: host
    command: filebrowser --port 3000 --scope /data
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
