version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: unless-stopped
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
  mqtt:
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
  node-red:
    build:
      context: ./host-images/node-red
    volumes:
      - "resin-data:/data"
    ports:
      - "1880:1880"
    depends_on:
      - mqtt
    restart: always
  nginx:
    build:
      context: ./host-images/nginx
    depends_on:
      - node-red
    ports:
      - "80:80"
      - "443:443"
    restart: always
  debug:
    image: pckzs/pybombs
    command: "sleep infinity"
    privileged: true
    volumes:
      - "resin-data:/data"
