version: "2"
volumes:
  resin-data: {}
services:
  mqtt:
    container_name: mqtt
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/mqtt
    volumes:
      - "./data:/data"
    restart: always
    ports:
      - "1883"
  netdata:
    image: sibylvision/netdata
    container_name: netdata
    hostname: edge.sibyl.vision
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
    cpu_shares: 150
  trunk-recorder:
    container_name: trunk-recorder
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/trunk-recorder
    privileged: true
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "./data:/data"
    environment:
      - RECORDER_CONF=sites/SF-PK/config.json
      - SHORTNAME=SFPD
      - MQTT_HOST=mqtt
    restart: on-failure
    cpuset: "0-4"
  ngrok:
    links:
      - nginx:https
    container_name: ngrok
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/ngrok
    privileged: false
    depends_on:
      - nginx
    command: ngrok tls -region=us -authtoken=iiX4RYrrdFWgU9pdDEnR_4qRcocGF5v9E3SjGmys7L -hostname=edge.sibyl.vision nginx:443
  config:
    container_name: config
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "./data:/data"
  manager:
    container_name: manager
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/manager
    volumes:
      - "./data:/data"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - NETDATA_HTTP=https://edge.sibyl.vision/netdata/
      - GRAPHQL_HTTP=https://edge.sibyl.vision/graphql/
      - GRAPHQL_WS=wss://edge.sibyl.vision/graphql/
    restart: always
  datarouter:
    container_name: datarouter
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/data-router
    volumes:
      - "./data:/data"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - GRAPHQL_PORT=4000
      - MQTT_PORT=1883
    depends_on:
      - redis
  nginx:
    container_name: nginx
    depends_on:
      - manager
      - nodered
      - netdata
    build:
      dockerfile: arm-cross.dockerfile
      context: host-images/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./data:/data"
  nodered:
    container_name: nodered
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/node-red
    volumes:
      - "./data:/data"
    ports:
      - "1880:1880"
    environment:
      - NODE_ENV=production
    restart: always
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    container_name: redis
    volumes:
      - "./data:/data"
    ports:
      - "6379"
    restart: always
  nodeexporter:
    image: prom/node-exporter:v0.17.0
    container_name: nodeexporter
    user: root
    privileged: true
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "9100:9100"
    network_mode: host
    volumes:
      - "./data:/data"
    labels:
      org.label-schema.group: "monitoring"
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
  prometheus:
    build:
      dockerfile: arm-cross.dockerfile
      context: host-images/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    volumes:
      - "./data:/data"
    ports:
      - "9090:9090"
    labels:
      org.label-schema.group: "monitoring"
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
  alertmanager:
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/alertmanager
    container_name: alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/data/alertmanager"
    restart: unless-stopped
    ports:
      - 9093
    labels:
      org.label-schema.group: "monitoring"
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - "8080:8080"
    command:
      - "--uri_base_prefix /cadvisor"
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    build:
      dockerfile: arm-cross.dockerfile
      context: ./host-images/grafana
    container_name: grafana
    entrypoint: /setup.sh
    volumes:
      - "./data:/data"
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_PATHS_DATA=/data/grafana/"
      - "GF_SERVER_HTTP_PORT=9900"
    restart: unless-stopped
    ports:
      - "9900:9900"
    labels:
      org.label-schema.group: "monitoring"
      io.balena.features.dbus: "1"
      io.balena.features.balena-socket: "1"
  pushgateway:
    image: prom/pushgateway:v0.7.0
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"
    labels:
      org.label-schema.group: "monitoring"
