version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: "no"
    depends_on:
      - "config"
    network_mode: host
    cpuset: 0-3
    volumes:
      - "resin-data:/data"
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
  data-browser:
    build:
      context: ./host-images/data-browser
    network_mode: host
    restart: "no"
    ports:
      - 8000:8000
    volumes:
      - "resin-data:/data"
