version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  # manager:
  #   build:
  #     context: ./host-images/host-manager
  #   privileged: true
  #   restart: "no"
  #   network_mode: host
  #   volumes:
  #     - "resin-data:/data"
  #   labels:
  #     io.resin.features.kernel-modules: "1"
  #     io.resin.features.firmware: "1"
  #     io.resin.features.dbus: "1"
  #     io.resin.features.supervisor-api: "1"
  #     io.resin.features.resin-api: "1"
  # soapy-remote:
  #   build:
  #     context: ./host-images/soapy-remote
  #   privileged: true
  #   restart: "no"
  #   depends_on:
  #     - "config"
  #   network_mode: host
  #   volumes:
  #     - "resin-data:/data"
  #   labels:
  #     io.resin.features.kernel-modules: "1"
  #     io.resin.features.firmware: "1"
  #     io.resin.features.dbus: "1"
  #     io.resin.features.supervisor-api: "1"
  #     io.resin.features.resin-api: "1"
  trunk-recorder:
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: "no"
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
  wifi-connect:
    build:
      context: ./host-images/wifi-connect
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.supervisor-api: "1"
      io.resin.features.resin-api: "1"
      io.balena.features.kernel-modules: "1"
      io.balena.features.firmware: "1"
      io.balena.features.supervisor-api: "1"
      io.balena.features.resin-api: "1"
  trunk-player:
    build:
      context: ./host-images/trunk-player
    network_mode: host
    restart: "no"
    depends_on:
      - "redis"
      - "postgres"
      - "nginx"
    volumes:
      - "resin-data:/data"
  postgres:
    build:
      context: ./host-images/postgres
    volumes:
      - "resin-data:/data"
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: skyscraper
      POSTGRES_PASSWORD: sdr
      PGDATA: /data/postgres
      POSTGRES_DB: radio
  redis:
    build:
      context: ./host-images/redis
    restart: "no"
    network_mode: host
  nginx:
    build:
      context: ./host-images/nginx
    privileged: true
    volumes:
      - "resin-data:/data"
    restart: "no"
    network_mode: host
    ports:
      - 80:80
