version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  trunk-recorder:
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: "no"
    depends_on:
      - "config"
    network_mode: host
    cpuset: 0-3
    volumes:
      - "resin-data:/data"
  config:
    build:
      context: ./host-images/config
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
  node-red:
    build:
      context: ./host-images/node-red
    environment:
      - USERNAME=skyscraper
      - PASSWORD=radio
    network_mode: host
    restart: "no"
    volumes:
      - "resin-data:/data"
