version: "2.1"
volumes:
  resin-data: {}
services:
  trunk-recorder:
    container_name: trunk-recorder
    build:
      context: ./host-images/trunk-recorder
    privileged: true
    restart: unless-stopped
    depends_on:
      - "config"
    network_mode: host
    volumes:
      - "resin-data:/data"
    environment:
      - RECORDER_CONF
  config:
    container_name: config
    build:
      context: ./host-images/config
    network_mode: host
    restart: "on-failure"
    volumes:
      - "resin-data:/data"
    