version: 2
jobs:
  build:
    docker:
      - image: docker:stable-dind
    working_directory: ~/repo
    steps:
      - run:
          name: Install Docker Compose
          command: |
            apk update
            apk add curl py-pip python build-base
            pip install docker-compose
      - checkout
      - run:
          command: |
            cd ~/repo
            docker-compose -f docker-compose.amd.yml build --parallel
workflows:
  version: 2
  build:
    jobs:
      - build
