version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    working_directory: ~/repo
    steps:
      - run:
          name: Install Docker Compose
          command: |
            apk update
            apk add curl py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
            curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: |
            cd ~/repo
            /usr/local/bin/docker-compose -f docker-compose.amd.yml build --parallel
workflows:
  version: 2
  build:
    jobs:
      - build
