version: 2
jobs:
  build:
    docker:
      - image: docker/compose:latest
    working_directory: ~/repo
    steps:
      - run:
          name: Install Deps
          command: |
            apk update
            apk add git openssh-client
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: |
            cd ~/repo
            docker-compose -f docker-compose.amd.yml build --parallel
workflows:
  version: 2
  build:
    jobs:
      - build
