FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node as build

RUN apk add --no-cache \
  bash \
  openssh \
  git \
  && rm -rf /var/cache/apk/*

COPY keys/* /root/.ssh/

RUN chmod 600 /root/.ssh/id_rsa && eval $(ssh-agent -s) \
  && cat /root/.ssh/id_rsa | ssh-add - \
  && ssh-keyscan github.com >> ~/.ssh/known_hosts

ENV CACHEBUST=23
ENV VUE_APP_GRAPHQL_HTTP https://edge.sibyl.vision/
ENV VUE_APP_GRAPHQL_WS wss://edge.sibyl.vision/subscriptions

RUN apk add --no-cache --virtual .build-deps alpine-sdk python && \
  git clone git@github.com:kazazes/skyscraper-manager.git /app && \
  cd /app && \
  git checkout nuxt && \
  cd /app/data-router && \
  yarn install --pure-lockfile --network-timeout 180000 && \
  NODE_ENV=production yarn run build

EXPOSE 4000
EXPOSE 1888

COPY docker-entrypoint.sh /usr/local/bin

ENTRYPOINT '/usr/local/bin/docker-entrypoint.sh'
