version: '3.5'

services:
  listener:
    env_file: .env
    build:
      context: .
    restart: unless-stopped
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf/mosquitto/config/mosquitto.conf
  server:
    image: ${MODELSERVER_IMAGE}
    command: python start_server.py
    environment:
      SKIP_DECODER: 1
    expose:
      - 9999
    ports:
      - 9999:9999
    restart: always
    links:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  worker:
    image: ${MODELSERVER_IMAGE}
    command: python start_worker.py
    environment:
      LOGLEVEL: 'DEBUG'
    restart: always
    links:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  redis:
    image: redis
