subscription {
  trunkedCalls {
    id
    createdAt
    frequency
    startTime
    endTime
    emergency
    talkgroup {
      decimal
      alphaTag
      description
      tag
    }
    system {
      id
      shortName
      type
    }
    duration
    audioPath
  }
}
